[package]
name = "somgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = "0.5.14"
lazy_static = "1.4.0"
eyre = "0.6.12"
nix = { version = "0.28.0", features = ["user"] }
libc = "0.2.153"
cmd_lib = "1.9.3"
subprocess = "0.2.9"