[package]
name = "somgr"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stblib = "0.6.2"
lazy_static = "1.4.0"
eyre = "0.6.12"
nix = { version = "0.29.0", features = ["user"] }
libc = "0.2.155"
cmd_lib = "1.9.4"
subprocess = "0.2.9"