name: Release Rust Binary (aarch64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the binary
        run: . $HOME/.cargo/env && cargo build --release && mv target/release/somgr target/release/somgr-aarch64

      - uses: actions/upload-artifact@v4
        with:
          name: somgr
          path: target/release/somgr-aarch64

      - uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: false
          name: "Latest Build"
          files: target/release/somgr-aarch64