name: Release somgr on GitHub

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install dependencies
        run: sudo apt install libdbus-1-dev pkg-config
          
      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
        name: somgr
        path: |
          target/release/somgr

      - uses: softprops/action-gh-release@v2
        if: github.repository == 'Strawberry-Foundations/somgr' && github.ref == 'refs/heads/main'
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            target/release/somgr