name: Release somgr on GitHub

on:
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install dependencies
        run: sudo apt install libdbus-1-dev pkg-config
          
      - name: Build
        run: cargo build --release

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: target/release/somgr
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
