name: Release Rust Binary (aarch64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - name: Install dependencies
        run: echo deb http://ports.ubuntu.com/dists/jammy/ arm64 main | sudo tee -a /etc/apt/sources.list && sudo apt update && sudo apt-get install pkg-config libssl-dev:arm64 binutils gcc-aarch64-linux-gnu libc6-arm64-cross libstdc++-10-dev-arm64-cross build-essential

      - name: Build the binary
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest Release
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/release/somgr
          asset_name: somgr-aarch64
          asset_content_type: application/octet-stream
