name: Release Rust Binary (x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: sudo apt-get install pkg-config libssl-dev

      - name: Build the binary
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: somgr
          path: target/release/somgr

      - uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: false
          name: "Latest Build"
          files: target/release/somgr